[package]
description = " Netfilter NFLOG high-level bindings"
license = "GPL-2.0+"

name = "nflog"
version = "0.9.0"
authors = [ "Pierre Chifflier <chifflier@wzdftpd.net>" ]

[dependencies]
libc = "0.2.0"
